name: Unittests
on: [push]

jobs:
  Py37_Ubuntu1804:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

    - name: Set up MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3307 # Optional, default value is 3306. The port of container
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql database: 'todo' # Optional, default value is "test". The specified database which will be create
        mysql root password: 'default' # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'default' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'default' # Required if "mysql user" exists. The password for the "mysql user"

    - name: Dump data into MySQL
      run : |
        mysqladmin -u root -p status
        sudo chmod -R 755 /var/lib/mysql/
        mysql -u root -p todo < python/setup_db.sql

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py

  Py37_Ubuntu1604:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py

  Py36_Ubuntu1804:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py

  Py36_Ubuntu1604:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py
