name: Unittests
on: [pull_request]

jobs:
  Py37_Ubuntu1804:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py

  Py37_Ubuntu1604:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py

  Py36_Ubuntu1804:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py

  Py36_Ubuntu1604:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        cd python
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Unittests
      run: |
        cd python/src
        python server.py -unittest &
        cd ..
        python tests/start.py
